In [10]:
from sklearn.datasets import load_diabetes
import torch
import torch.nn as nn

In [9]:
dataset = load_diabetes()
dataset['data']
dataset['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [21]:
dataset['data'].shape[0]
len(dataset['data'])//64

6

In [25]:
Y = torch.tensor(dataset['target'], dtype=torch.int64)
Y

tensor([151,  75, 141, 206, 135,  97, 138,  63, 110, 310, 101,  69, 179, 185,
        118, 171, 166, 144,  97, 168,  68,  49,  68, 245, 184, 202, 137,  85,
        131, 283, 129,  59, 341,  87,  65, 102, 265, 276, 252,  90, 100,  55,
         61,  92, 259,  53, 190, 142,  75, 142, 155, 225,  59, 104, 182, 128,
         52,  37, 170, 170,  61, 144,  52, 128,  71, 163, 150,  97, 160, 178,
         48, 270, 202, 111,  85,  42, 170, 200, 252, 113, 143,  51,  52, 210,
         65, 141,  55, 134,  42, 111,  98, 164,  48,  96,  90, 162, 150, 279,
         92,  83, 128, 102, 302, 198,  95,  53, 134, 144, 232,  81, 104,  59,
        246, 297, 258, 229, 275, 281, 179, 200, 200, 173, 180,  84, 121, 161,
         99, 109, 115, 268, 274, 158, 107,  83, 103, 272,  85, 280, 336, 281,
        118, 317, 235,  60, 174, 259, 178, 128,  96, 126, 288,  88, 292,  71,
        197, 186,  25,  84,  96, 195,  53, 217, 172, 131, 214,  59,  70, 220,
        268, 152,  47,  74, 295, 101, 151, 127, 237, 225,  81, 1

In [26]:
Y[64:128]

tensor([ 71, 163, 150,  97, 160, 178,  48, 270, 202, 111,  85,  42, 170, 200,
        252, 113, 143,  51,  52, 210,  65, 141,  55, 134,  42, 111,  98, 164,
         48,  96,  90, 162, 150, 279,  92,  83, 128, 102, 302, 198,  95,  53,
        134, 144, 232,  81, 104,  59, 246, 297, 258, 229, 275, 281, 179, 200,
        200, 173, 180,  84, 121, 161,  99, 109])

In [30]:
# 데이터셋
X = torch.tensor(dataset['data'], dtype=torch.float32)
Y = torch.tensor(dataset['target'], dtype=torch.int64)

# 모델만들기
model = nn.Sequential(
    nn.Linear(10, 64),
    nn.ReLU(), 
    nn.Linear(64, 16),
    nn.ReLU(), 
    nn.Linear(16, 1)
)
    
# 하이퍼 파라미터 정하기
batch_size = 64
learning_rate = 1e-4   
epochs = 3001

# 옵티마이저 만들기
optimizer = torch.optim.SGD(params= model.parameters(), lr=learning_rate ) 

# 학습하기
for epoch in range(epochs): 

    for i in range(len(X)//batch_size):   # 배치사이즈만큼 공급하기
        start = i*batch_size
        end = (i+1)*batch_size

        x = X[start:end]
        y = Y[start:end]
            
        optimizer.zero_grad()                      # 각 변수의 기울기 초기화    
        y_pred = model(x)                         # 순전파    
        criterion = nn.MSELoss()   # 손실함수 정의   
        loss = criterion(y_pred, y)              # 손실 계산    
        loss.backward()                          # backward  : 미분해서 기울기 다 찾아두기     
        optimizer.step()                         # 가중치 a,b,c,d 업데이트   
   
    if epoch % 1000 == 0:
        print(f"epoch: {epoch},  loss: {loss}")


epoch: 0,  loss: 33498.98828125
epoch: 1000,  loss: 6062.50146484375
epoch: 2000,  loss: 6061.30419921875
epoch: 3000,  loss: 6060.7236328125


In [32]:
list(model.parameters())

[Parameter containing:
 tensor([[ 1.9782e-01, -8.1119e-03, -1.8900e-01,  2.2964e-01, -1.3992e-01,
          -1.6281e-01,  1.4437e-02, -2.8663e-01, -1.5962e-01,  5.9168e-02],
         [-2.2433e-01, -9.9553e-02, -3.0529e-02,  1.3395e-01, -1.6350e-01,
          -1.6534e-01,  2.4906e-01,  1.9086e-01,  2.5218e-01,  1.6639e-01],
         [ 2.2786e-01, -1.7638e-01, -1.3105e-02, -2.0167e-01, -2.2231e-01,
          -1.5234e-01,  5.0492e-02, -1.6919e-01,  1.3276e-01,  2.2436e-01],
         [-8.8946e-02, -2.9218e-01,  1.7522e-01, -3.1818e-02,  1.5836e-01,
           1.8500e-01, -2.9515e-01,  3.5753e-01,  1.4454e-02, -9.0310e-02],
         [-1.0520e-01, -2.7469e-01, -2.5854e-01, -2.7150e-01, -7.7340e-02,
          -9.8988e-02,  1.4115e-01, -1.8528e-01, -2.2020e-01, -1.2202e-01],
         [ 1.4272e-01,  1.0506e-01,  2.8619e-01,  2.2837e-02, -2.1023e-01,
          -1.5808e-01, -3.3200e-02,  2.9962e-01, -1.6417e-01,  3.2612e-01],
         [-3.0150e-01, -2.2260e-01,  2.0055e-01,  3.1224e-01,  4.0758e-

In [39]:
y_pred = model(X)
((y_pred - Y)**2).mean()  # MSE 
((y_pred - Y)**2).mean().sqrt()  # RMSE 
(y_pred - Y).abs().mean()  # MAE 

tensor(77.2514, grad_fn=<SqrtBackward0>)

In [45]:
X[100:101]

tensor([[ 0.0163, -0.0446,  0.0175, -0.0229,  0.0603,  0.0444,  0.0302, -0.0026,
          0.0372, -0.0011]])

In [42]:
y_pred = model(X[100:101])

In [44]:
y_pred.item()

157.0611572265625