In [1]:
from sklearn.datasets import load_iris

dataset = load_iris()

In [4]:
dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

##  데이터셋 만들기

In [5]:
import torch
from torch.utils.data  import Dataset
from sklearn.model_selection import train_test_split

In [24]:
class IrisDataset(Dataset):
    def __init__(self, train=True):
        dataset = load_iris()
        X_train, X_test, y_train, y_test = train_test_split(dataset['data'], dataset['target'], 
                                                            test_size=.3, random_state=827)

        if train:
            self.data = torch.tensor(X_train, dtype=torch.float32)
            self.target = torch.tensor(y_train, dtype=torch.int64)
        else:
            self.data = torch.tensor(X_test, dtype=torch.float32)
            self.target = torch.tensor(y_test, dtype=torch.int64)

    def __getitem__(self, i):
       return self.data[i], self.target[i]

    def __len__(self):
        return len(self.data)

In [26]:
a = IrisDataset()

In [27]:
a.__len__()

105

In [28]:
len(a)

105

In [29]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

In [31]:
# 하이퍼파라미터
batch_size = 64
learning_rate = 1e-3
epochs = 200

# 모델
model = nn.Sequential(
    nn.Linear(4, 128),
    nn.ReLU(),
    nn.Linear(128, 64),
    nn.ReLU(),
    nn.Linear(64, 3)
)

# 데이터셋, 데이터로더
train_dataset = IrisDataset(train=True)
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# optimizer
optimizer = torch.optim.Adam(params=model.parameters(), lr=learning_rate)

# loss
criterion = nn.CrossEntropyLoss()

for epoch in range(epochs):

  # 배치
  for data, target in train_dataloader:
    optimizer.zero_grad()
    pred = model(data)
    loss = criterion(pred, target)
    loss.backward()
    optimizer.step()

  # 학습 기록
  if epoch % 10 == 1:
    print("epoch:", epoch+1, "loss:", loss.item())

epoch: 2 loss: 1.0057100057601929
epoch: 12 loss: 0.579920768737793
epoch: 22 loss: 0.3939548134803772
epoch: 32 loss: 0.28448760509490967
epoch: 42 loss: 0.16874179244041443
epoch: 52 loss: 0.18343372642993927
epoch: 62 loss: 0.11970886588096619
epoch: 72 loss: 0.09802038222551346
epoch: 82 loss: 0.09859495609998703
epoch: 92 loss: 0.09493768215179443
epoch: 102 loss: 0.12306570261716843
epoch: 112 loss: 0.10910610109567642
epoch: 122 loss: 0.07261162996292114
epoch: 132 loss: 0.06518090516328812
epoch: 142 loss: 0.04333191365003586
epoch: 152 loss: 0.03279981389641762
epoch: 162 loss: 0.0490792915225029
epoch: 172 loss: 0.037073612213134766
epoch: 182 loss: 0.03207405284047127
epoch: 192 loss: 0.06455587595701218


In [34]:
list(model.parameters())

[Parameter containing:
 tensor([[-1.3781e-01, -2.3319e-03, -2.5553e-01,  8.3988e-02],
         [ 3.4090e-01,  4.6241e-01, -4.7070e-01, -5.1696e-01],
         [-1.2508e-01, -3.5452e-01,  3.1314e-01, -4.3053e-01],
         [ 2.3034e-01, -7.8480e-02, -4.0894e-01, -3.9442e-01],
         [-1.6930e-01, -7.3486e-02,  5.6751e-01,  1.0455e-02],
         [ 4.1910e-01, -4.6168e-01,  3.9663e-01, -2.0472e-01],
         [ 3.7983e-01, -9.9063e-02, -3.4594e-01, -2.0333e-02],
         [-2.4122e-01, -3.6638e-01, -3.2546e-01, -6.8768e-02],
         [-1.4899e-01,  1.1406e-01,  5.3483e-04,  3.3144e-01],
         [ 4.4998e-01, -2.9392e-01,  5.6201e-01, -8.8747e-03],
         [-4.7649e-01, -2.1921e-01, -1.2294e-01,  2.3824e-01],
         [ 2.1092e-01,  1.0371e-01,  3.8192e-01, -3.8991e-01],
         [ 3.3694e-01,  2.4462e-01, -1.5581e-01, -5.9905e-01],
         [ 4.2233e-01, -5.1045e-01,  1.5220e-01,  4.7864e-02],
         [-4.7041e-01,  3.1938e-01,  4.0109e-01, -3.6086e-01],
         [ 3.9768e-01,  2.7252e-

In [35]:
test_dataset = IrisDataset(train=False)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

num_correct = 0

with torch.no_grad():
  for data, target in test_dataloader:
    output = model(data)
    pred = torch.max(output, 1)[1]

    corr = pred.eq(target).sum().item()
    num_correct += corr

  print("Accuracy:", (num_correct/len(test_dataset.data))*100, "%")

Accuracy: 100.0 %


In [46]:
torch.max(output, axis=1)[1]

tensor([0, 2, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 0,
        0, 0, 0, 2, 0, 2, 2, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1])

In [41]:
num_correct
corr
pred
output

tensor([[ 13.0855,   5.5787, -15.6437],
        [-12.0450,   1.0747,   7.5315],
        [ -7.2029,   2.2902,   3.2460],
        [ 12.4350,   5.4122, -14.9103],
        [-12.0949,  -0.5253,   8.6894],
        [-11.9201,   1.0783,   7.4368],
        [ 12.9576,   5.4949, -15.4240],
        [ -6.8884,   2.3422,   2.9821],
        [-10.8285,   0.7425,   6.9506],
        [ -2.4993,   4.6271,  -1.8905],
        [ -4.9724,   4.5835,  -0.0660],
        [ 11.1703,   5.2431, -13.7111],
        [-10.2501,   0.9006,   6.4215],
        [ -2.6650,   4.8733,  -1.9296],
        [-13.5625,   0.4633,   9.0154],
        [ 12.8457,   5.5787, -15.3851],
        [-11.5236,   1.3078,   6.9986],
        [ -9.6629,   0.5672,   6.2696],
        [ -9.1394,   0.5355,   5.9330],
        [ 13.4475,   5.9476, -16.2228],
        [ -7.2139,   2.3925,   3.1875],
        [ 12.0089,   5.1354, -14.3219],
        [ 11.7515,   5.3934, -14.3027],
        [ 11.2186,   5.1508, -13.6620],
        [ 12.4072,   5.6052, -15.0547],


In [42]:
pred

tensor([0, 2, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 0,
        0, 0, 0, 2, 0, 2, 2, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1])