In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
li1 = [1,2,3,4]
li2 = [1,2,3,4]
li1 + li2 

[1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
# element-wise
arr1 = np.array(li1)
arr2 = np.array(li2)
arr1 + arr2

array([2, 4, 6, 8])

In [119]:
import torch
torch.tensor(li1)
torch.tensor(arr1)

tensor([1, 2, 3, 4])

In [114]:
np.random.rand()
np.random.rand(2, 3)
np.random.randint(10)
np.random.randint(1, 11)
np.random.randint(1, 11, size=(2,3))
np.random.randn(10)
np.random.randn(2, 5)

array([[ 0.96127399, -0.08973065,  1.42226533, -0.76126148,  1.08112708],
       [ 0.77683345,  1.70240282,  2.02726083,  0.3970646 ,  1.01077022]])

In [125]:
torch.rand(2)
torch.rand(2,3)

tensor([[0.3633, 0.8749, 0.9699],
        [0.0926, 0.4742, 0.8104]])

In [136]:
torch.randint( 10, size= (2,3))
torch.randint(1, 11, size= (2,3))

tensor([[ 8, 10, 10],
        [ 8,  3,  5]])

In [140]:
t = torch.randn(size=(2,3))
t

tensor([[ 0.0343, -0.4004, -0.4112],
        [-1.4437, -0.8015, -0.0149]])

In [139]:
t.shape

torch.Size([2, 3])

In [143]:
t.dim()

2

In [141]:
t[:, :2]

tensor([[ 0.0343, -0.4004],
        [-1.4437, -0.8015]])

In [145]:
t = torch.randint( 11, size=(2,3,4))
t

tensor([[[ 5,  0,  0, 10],
         [ 5,  2,  2,  9],
         [ 0,  0,  3,  0]],

        [[ 0,  8,  7,  6],
         [ 6,  9, 10,  4],
         [ 5,  1,  5,  3]]])

In [146]:
t.dim()

3

In [147]:
t.shape

torch.Size([2, 3, 4])

In [151]:
t[0, :, : ]  +  t[1, :, : ] 

tensor([[ 5,  8,  7, 16],
        [11, 11, 12, 13],
        [ 5,  1,  8,  3]])

- 2행 3열짜리 텐서 만들기

In [154]:
torch.randint( 10, size=(2,3))

tensor([[2, 7, 3],
        [8, 1, 0]])

In [156]:
t = torch.zeros((2,3))
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [163]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [158]:
t[0, :] = torch.tensor([1,2,3])
t[1, :] = torch.tensor([11,12,13])
t

tensor([[ 1.,  2.,  3.],
        [11., 12., 13.]])

In [160]:
t = torch.randint( 10, size=(3,3))
t

tensor([[1, 3, 0],
        [3, 1, 7],
        [6, 3, 9]])

In [162]:
torch.zeros_like(t)
torch.empty_like(t)

tensor([[127219929,         0,         0],
        [        0,         0,         0],
        [        0,         0,         0]])

In [167]:
t = torch.zeros((3,3))
t[2,2] = 1
t

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])

In [180]:
np.arange(10)

# 2행 5열짜리 0~9까지인 행렬
np.arange(10).reshape(2,5)

 # 1부터 24까지 2x3x4 인 3차원 array를 만들어 주세요 (2,3,4)
 # 1부터 24까지 2x3x4 인 3차원 tensor를 만들어 주세요 (2,3,4)
np.arange(1,25).reshape(2,3,4)
torch.arange(1,25).reshape(2,3,4)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [182]:
torch.tensor(np.arange(1,25).reshape(2,3,4))

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [173]:
arr = np.arange(10)
arr.shape

(10,)

In [190]:
arr1 = np.array([1,2])
arr2 = np.array([[1,2],[3,4]])
arr1 + arr2 

array([[2, 4],
       [4, 6]])

In [192]:
arr1 + 5

array([6, 7])

In [198]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[10],[20],[30],[40],[50]])
arr1 + arr2

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [201]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.arange(10, 51, step=10).reshape(5, 1)
arr1 + arr2

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [203]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.arange(100, 701, step=100).reshape(7, 1)
arr1 + arr2

array([[101, 102, 103, 104, 105, 106, 107],
       [201, 202, 203, 204, 205, 206, 207],
       [301, 302, 303, 304, 305, 306, 307],
       [401, 402, 403, 404, 405, 406, 407],
       [501, 502, 503, 504, 505, 506, 507],
       [601, 602, 603, 604, 605, 606, 607],
       [701, 702, 703, 704, 705, 706, 707]])

In [204]:
tensor1 = torch.tensor([1,2,3,4,5,6,7])
tensor2 = torch.arange(100, 701, step=100).reshape(7, 1)
tensor1 + tensor2

tensor([[101, 102, 103, 104, 105, 106, 107],
        [201, 202, 203, 204, 205, 206, 207],
        [301, 302, 303, 304, 305, 306, 307],
        [401, 402, 403, 404, 405, 406, 407],
        [501, 502, 503, 504, 505, 506, 507],
        [601, 602, 603, 604, 605, 606, 607],
        [701, 702, 703, 704, 705, 706, 707]])

In [208]:
t = torch.arange(1, 5).reshape(2,2)
t

tensor([[1, 2],
        [3, 4]])

In [212]:
t.sum()
t.sum(axis=0)
t.sum(axis=1)
t.sum(dim=1)

tensor([3, 7])

In [213]:
t.shape

torch.Size([2, 2])

In [216]:
t

tensor([[1, 2],
        [3, 4]])

In [215]:
t.argmax(axis=0)

tensor([1, 1])

In [217]:
t.argmax(axis=1)

tensor([1, 1])

In [220]:
t = torch.arange(1,7).reshape(1,2,3)
t

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [221]:
t.shape

torch.Size([1, 2, 3])

In [224]:
t.permute([2,1,0])
t.permute([2,1,0]).shape

torch.Size([3, 2, 1])

In [226]:
t.permute([1,2,0])

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [228]:
t
t.shape

torch.Size([1, 2, 3])

In [232]:
t.squeeze()
t.squeeze().shape

torch.Size([2, 3])

In [234]:
t.shape

torch.Size([1, 2, 3])

In [235]:
t1 = t.permute([1, 0 , 2])
t1
               

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [237]:
t1.shape

torch.Size([2, 1, 3])

In [239]:
t.squeeze().shape

torch.Size([2, 3])

In [245]:
t = torch.arange(10, 61, step=10).reshape(2,3)
t

tensor([[10, 20, 30],
        [40, 50, 60]])

In [246]:
t.shape

torch.Size([2, 3])

In [247]:
t.unsqueeze(0)

tensor([[[10, 20, 30],
         [40, 50, 60]]])

In [248]:
t.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [250]:
t.flatten()

tensor([10, 20, 30, 40, 50, 60])